SET search_path TO pettycash;

CREATE TABLE cash_transaction(
  transaction_id    bigint                    not null generated by default as identity,
  transaction_date  date                      not null,
  debit             boolean                   not null,
  amount            integer                   not null,
  clerk             text                      not null,
  comment           text,
  created_at        timestamp with time zone not null DEFAULT now(),
  created_by        uuid,
  updated_at        timestamp with time zone,
  updated_by        uuid,
  CONSTRAINT cash_transaction_pk PRIMARY KEY (transaction_id),
  CONSTRAINT cash_tran_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users
);

ALTER TABLE cash_transaction ENABLE ROW LEVEL SECURITY;

create or replace function trg_audit() returns trigger
language plpgsql as $$
begin
  case TG_OP
  when 'INSERT' then
    new.created_at := now();
    new.created_by := auth.uid();
    new.updated_at := null;
    new.updated_by := null;
  when 'UPDATE' then
    new.created_at := old.created_at;
    new.created_by := old.created_by;
    new.updated_at := now();
    new.updated_by := auth.uid();
  end case;

  return new;
end;
$$

create or replace trigger cash_transaction_biur
before insert or update on cash_transaction
for each row
execute function trg_audit()
